### ISSUE TITLE
AssertionError [ERR_ASSERTION]: The expression evaluated to a falsy value:    (0, _assert.default)(buf.length >= 4)

### ISSUE THREAD

**Issue by heineiuo** [heineiuo/node-level#90]
```ts
AssertionError [ERR_ASSERTION]: The expression evaluated to a falsy value:

  (0, _assert.default)(buf.length >= 4)

    at decodeFixed32 (/node_modules/node-level/build/Coding.js:47:23)
    at SSTableBlock.restartPointIterator (/node_modules/node-level/build/SSTableBlock.js:82:39)
```

**Comment by heineiuo** [comment]
```ts
  *restartPointIterator(): IterableIterator<number> {
    let currentOffset = this._restartPoint
    while (true) {
      if (currentOffset >= this._size - 4) {
        break
      }
      yield decodeFixed32(this._buffer.slice(currentOffset, currentOffset + 4))
      currentOffset += 4
    }
  }
```

weirdly
